export default function preload (){
  this.load.image('space', 'assets/start_bkgd.jpg')
  this.load.image('title', 'assets/start_title.png')
  this.load.spritesheet('asteroids', 'assets/asteroids.png', { frameWidth: 70, frameHeight: 65 })
  this.load.image('asteroid0','assets/asteroid12.png')
  this.load.image('asteroid1','assets/asteroid1.png')
  this.load.image('asteroid2','assets/asteroid2.png')
  this.load.image('asteroid3','assets/asteroid3.png')
  this.load.image('asteroid4','assets/asteroid4.png')
  this.load.image('asteroid5','assets/asteroid5.png')
  this.load.image('asteroid6','assets/asteroid6.png')
  this.load.image('asteroid7','assets/asteroid7.png')
  this.load.image('asteroid8','assets/asteroid8.png')
  this.load.image('asteroid9','assets/asteroid9.png')
  this.load.image('asteroid10','assets/asteroid10.png')
  this.load.image('asteroid11','assets/asteroid11.png')
  this.load.spritesheet('ship', 'assets/ship.png', { frameWidth: 90, frameHeight: 90 })
  this.load.image('laserGreen', 'assets/laserGreenR.png')
  this.load.image('laserBlue', 'assets/laserBlueR.png')
  this.load.image('shield1', 'assets/shield1.png')
  this.load.image('shield2', 'assets/shield2.png')
  this.load.image('shield_powerup', 'assets/shield_gold.png')
  this.load.image('star_powerup', 'assets/star_gold.png')
  this.load.image('gold_powerup', 'assets/bolt_gold.png')
  this.load.image('silver_powerup', 'assets/bolt_silver.png')
  this.load.image('ship_shield1', 'assets/ship_shield1.png')
  this.load.image('ship_shield2', 'assets/ship_shield2.png')
}